// Hostinger Node.js startup entry.
// The production build generated by Nitro is the actual HTTP server.
// Hostinger can use this stable root-level entry file even when framework
// auto-detection does not recognize TanStack Start.
await import("./.output/server/index.mjs");
